### ISSUE TITLE
0.1.8 has been pushed to the groovy.yaml

### ISSUE THREAD

**Issue by vrabaud** [stonier/zeroconf_avahi_suite#1]
But somehow not released. Should we revert to 0.1.7 on the ROS farm ? Thx

**Comment by stonier** [comment]
I can do it - Mel kicked me about naming so I converted zeroconf_comms -> zeroconf_msgs, but that was having issues releasing, so this was immediately pending.

I'll have another attempt right now and update within the hour.

**Comment by vrabaud** [comment]
sounds good. BTW, the demos always fail:
http://jenkins.willowgarage.com:8080/view/GbinP64/job/ros-groovy-zeroconf-avahi-demos_binarydeb_precise_amd64/6/console

**Comment by stonier** [comment]
Ok, releases are blooming and I think it was the include installation missing its tail ('/') above that caused it to go awry, so now just to wait on genteel jenkins to do his job.

Getting the hang of bloom.
